import { Outfit, Ovo } from "next/font/google";
import "./globals.css";

const Outfits = Outfit({
  subsets: ["latin"], weight: ["400", "500", "600", "700"],
});

const Ovos = Ovo({
  subsets: ["latin"], weight: ["400"],
});

export const metadata = {
  title: "Portfolio - Akbar Maulana",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${Outfits.className} ${Ovos.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
